import { Inter } from "next/font/google";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";
import Navbar from "./components/Navbar";
import { StoreProvider } from "./StoreProvider";
import Header from "./components/Header";
import StyledComponentsRegistry from "./lib/register";
import { ToastContainer } from "react-toastify";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Navbar /> */}
        <StyledComponentsRegistry>
          <StoreProvider>
            <Header/>
            <Navbar/>
            {children}
            </StoreProvider>
          <ToastContainer
            position="bottom-right"
            autoClose={5000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="colored"
          />
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
